# Generated by Django 4.1.7 on 2023-02-22 21:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('current_status', models.TextField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=10)),
                ('adm_number', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('date_of_admission', models.DateField(auto_now_add=True)),
                ('address', models.TextField(max_length=120)),
                ('date_of_birth', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('current_status', models.TextField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=10)),
                ('tsc_number', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('full_name', models.TextField(max_length=200)),
                ('surname', models.TextField(max_length=200)),
                ('gender', models.TextField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('address', models.CharField(max_length=15)),
                ('phone_number', models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message="Entered mobile number isn't in a right format!", regex='^[0-9]{10,15}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Parents',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message="Entered mobile number isn't in a right format!", regex='^[0-9]{10,15}$')])),
                ('email', models.EmailField(max_length=200)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.student')),
            ],
        ),
        migrations.CreateModel(
            name='ClassTeachers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.teacher')),
            ],
        ),
    ]
