from django.urls import path

from .views import (
    ClassCreateView,
    ClassDeleteView,
    ClassListView,
    ClassUpdateView,
    CurrentYearAndTermView,
    IndexView,
    YearCreateView,
    YearDeleteView,
    YearListView,
    YearUpdateView,
    SubjectCreateView,
    SubjectDeleteView,
    SubjectListView,
    SubjectUpdateView,
    TermCreateView,
    TermDeleteView,
    TermListView,
    TermUpdateView,
)

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("current-year/", CurrentYearAndTermView.as_view(), name="current-year"),
    path("year/list/", YearListView.as_view(), name="years"),
    path("year/create/", YearCreateView.as_view(), name="year-create"),
    path("year/<int:pk>/update/",YearUpdateView.as_view(),name="year-update"),
    path("year/<int:pk>/delete/",YearDeleteView.as_view(),name="year-delete"),
    path("term/list/", TermListView.as_view(), name="terms"),
    path("term/create/", TermCreateView.as_view(), name="term-create"),
    path("term/<int:pk>/update/", TermUpdateView.as_view(), name="term-update"),
    path("term/<int:pk>/delete/", TermDeleteView.as_view(), name="term-delete"),
    path("class/list/", ClassListView.as_view(), name="classes"),
    path("class/create/", ClassCreateView.as_view(), name="class-create"),
    path("class/<int:pk>/update/", ClassUpdateView.as_view(), name="class-update"),
    path("class/<int:pk>/delete/", ClassDeleteView.as_view(), name="class-delete"),
    path("subject/list/", SubjectListView.as_view(), name="subjects"),
    path("subject/create/", SubjectCreateView.as_view(), name="subject-create"),
    path("subject/<int:pk>/update/",SubjectUpdateView.as_view(),name="subject-update"),
    path("subject/<int:pk>/delete/",SubjectDeleteView.as_view(),name="subject-delete"),
]
